name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest # ИСПОЛЬЗУЕМ WINDOWS

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install and Download SonarScanner
        run: |
          # 1. Скачиваем SonarScanner CLI
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "sonar-scanner-cli.zip"

          # 2. Устанавливаем 7-Zip (если он не установлен)
          if (-not (Get-Command 7z -ErrorAction SilentlyContinue)) {
            Write-Host "7-Zip не установлен. Устанавливаем..."
            & {
              Invoke-WebRequest -Uri "https://www.7-zip.org/a/7z2301-x64.exe" -OutFile "7z.exe"
              .\7z.exe /S
              Remove-Item "7z.exe"
            }
          }

          # 3. Создаём директорию sonar-scanner
          New-Item -ItemType Directory -Name sonar-scanner -ErrorAction SilentlyContinue

          # 4. Разархивируем в созданную директорию с помощью 7-Zip
          & "C:\Program Files\7-Zip\7z.exe" x "sonar-scanner-cli.zip" -o"sonar-scanner" -y

          # 5. Выводим список файлов и папок В КОРНЕВОЙ ДИРЕКТОРИИ
          Write-Host "Содержимое корневой директории:"
          Get-ChildItem -Path .

          # 6. Выводим список файлов и папок В ПАПКЕ sonar-scanner
          Write-Host "Содержимое папки sonar-scanner:"
          Get-ChildItem -Path "sonar-scanner"

      - name: Run SonarScanner
        run: |
          # Вызываем исполняемый файл напрямую (он должен быть в PATH, но вызываем явно)
          # В PowerShell используем ` ` для переноса строк

          # Пытаемся запустить сканер, предполагая стандартную структуру
          $scannerPath = ".\sonar-scanner\sonar-scanner-cli-5.0.1.3006-windows\bin\sonar-scanner.bat"

          # Проверяем, существует ли файл
          if (Test-Path -Path $scannerPath) {
            Write-Host "Файл sonar-scanner.bat найден по пути: $scannerPath"
            & $scannerPath `
              -Dsonar.projectKey=Fredrix24_caesarcipher `
              -Dsonar.organization=fredrix24 `
              -Dsonar.projectName="Caesar Cipher Project" `
              -Dsonar.sources=. `
              -Dsonar.sourceEncoding=UTF-8 `
              -Dsonar.host.url=https://sonarcloud.io `
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          } else {
            Write-Host "Ошибка: Файл sonar-scanner.bat НЕ найден по пути: $scannerPath"
            exit 1
          }