name: Build & SonarQube Analysis (Java)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Настройка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

          # 2. Сборка проекта (если требуется)
          # Если у вас Maven или Gradle, используйте соответствующие шаги
          # Пример для Maven:
          #- name: Build with Maven
          #  run: mvn clean install

      # 3. SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}