name: Build & SonarQube Analysis (Java with Maven)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. Настройка JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Компиляция Java кода с помощью Maven
      - name: Compile Java Code with Maven
        run: mvn compile

      # 3. SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_SCANNER_OPTS: >
            -Dsonar.java.binaries=target/classes
            -Dsonar.sources=src
            -Dsonar.tests=.